name       : subsurface-libdc
version    : 4.8.5
release    : 2
source     :
    - https://subsurface-divelog.org/downloads/libdivecomputer-subsurface-branch-4.8.5.tgz : d45da439f2e5492e9a4455f3ec78a2725cb696565bd9e81f33c26c403eacc4e7
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Subsurface version of libdivecomputer
description: |
    Subsurface version of libdivecomputer, a library for communication with dive computers from various manufacturers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
