name       : subsurface-libdc
version    : 4.9.3
release    : 3
source     :
    - https://github.com/Subsurface-divelog/libdc/archive/v4.9.3.tar.gz : 50c54f2d5e4f719e33442aee946e159852387bd208ac4b59dbd777097def42cf
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Subsurface version of libdivecomputer
description: |
    Subsurface version of libdivecomputer, a library for communication with dive computers from various manufacturers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
