name       : subsurface-libdc
version    : 4.9.8
release    : 5
source     :
    - https://github.com/Subsurface-divelog/libdc/archive/v4.9.8.tar.gz : 8c5aba5c21a6c6060e287a0e8257b2ef9257196fc8056b354fb467a9caee235b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Subsurface version of libdivecomputer
description: |
    Subsurface version of libdivecomputer, a library for communication with dive computers from various manufacturers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
